services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackaton-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackaton-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DOCKER: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}
    networks:
      - hackaton-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  hackaton-network: